package zftp

import "fmt"

var ErrIEF = fmt.Errorf("IEF error")
var ErrAba = fmt.Errorf("ABA error")
var ErrIEFAndABA = fmt.Errorf("IEF/ABA error")

var iefMessages = map[string]string{
	"IEF001I": "ERROR ON WRITE TO SYSTEM MESSAGE FILE",
	"IEF002W": "PENDING DEVICE PROCESSING MODULE IEFHBPDB HAS FAILED",
	"IEF003I": "jobname procstep stepname ddname + xxx - DD THAT IS CAUSING THE ABEND05C RC309",
	"IEF004I": "jobname procstep stepname ddname + xxxx ERROR PROCESSING UNIT AFFINITY REQUEST",
	"IEF005I": "jobname procstep stepname ddname + xxx - EDL CHANGED OUTSIDE ALLOCATION FOR DEVICE TYPE devtype",
	"IEF006I": "jobname RESTARTING AT xxxxxxxx K, yyyyyyyy K, aaaaaaaa K, bbbbbbbb K",
	"IEF007I": "RESTART NOT SUCCESSFUL FOR jobname (reason-code)",
	"IEF008I": "DASD DEVICE devnum NOT VARIED ONLINE - VOLUME SERIAL NOT VALID",
	"IEF009I": "CONCATENATE REQUEST FAILED - ACTUAL/CAPTURED UCB ATTRIBUTES OF SPECIFIED DD STATEMENTS DO NOT MATCH",
	"IEF010I": "CHECKPOINT RESTART OF JOB jobname ABENDED - code",
	"IEF011I": "jobname [procstep] stepname ddname[+ xxx] — DEVICE dev IS BOXED — CANNOT BE ALLOCATED",
	"IEF013I": "jobname CANNOT BE CANCELLED BECAUSE IT IS WAITING ON I/O",
	"IEF014I": "jobname [procstep] stepname ddname [+XXX] MAXIMUM GENERATED DDNAMES LIMIT REACHED",
	"IEF016I": "jobname procstep stepname ddname +xxx UNABLE TO ALLOCATE UNINITIALIZED SPOOL DATASET",
	"IEF017I": "jobname procstep stepname ddname +xxx FAILED TO UNLOAD VOLUME volser from DEVICE devnum - text",
	"IEF018I": "CRITICAL INTERNAL ALLOCATION TAPE PROCESSING ERROR DETECTED",
	"IEF019I": "jobname procstep stepname ddname +xxx THE ALLOCATED/OFFLINE EXIT, IEF_ALLC_OFFLN, DIRECTED ALLOCATION TO WAIT",
	"IEF020I": "jobname procstep stepname TCT I/O TABLE SIZE EXCEEDS THE 16MB MAXIMUM.",
	"IEF021I": "jobname [procstep] stepname ddname [+ xxx] EXTENDED ADDRESS VOLUME USE PREVENTED DUE TO SMS USEEAV(NO) SPECIFICATION.",
	"IEF022I": "jobname [procstep] stepname ddname [+ xxx] ALLOCATION FAILED - REQUESTED DEVICE IS MARKED UNAVAILABLE",
	"IEF023I": "jobname [procstep] stepname ddname [+ xxx] ALLOCATION FAILED - NOT ENOUGH ELIGIBLE LIBRARY DEVICES",
	"IEF024I": "DASD DEVICE devnum NOT VARIED ONLINE - VOLUME IS INITIALIZED TO REMAIN OFFLINE",
	"IEF030I": "VOLUME actvol DOES NOT MATCH REQUESTED VOLUME reqvol",
	"IEF031I": "DEVICE CANNOT BE USED",
	"IEF032I": "STEP/stepname/STOP yyyyddd.hhmm CPU: xxxxx HR xx MIN xx.xx SEC SRB: xxxxx HR xx MIN xx.xx SEC REAL/VIRT: xxxxxK  SYS: xxxxxK EXT: xxxxxxxxK  SYS: xxxxxxxxK ATB- REAL: xxxxxxxxxxxxxxxxxxxxK SLOTS: xxxxxxxxxxxxxxxxxxxxK VIRT- ALLOC: xxxxxxxM SHRD: xxxxxxxM",
	"IEF033I": "JOB/jobname/STOP yyyyddd.hhmm CPU: xxxxx HR xx MIN xx.xx SECSRB: xxxxx HR xx MIN xx.xx SEC",
	"IEF042I": "JOB CANCELLED BY INSTALLATION EXIT - xxxxxxxx",
	"IEF043I": "Actions taken by SMFLIMxx parmlib policy for jobname stepnameStep REGION BELOW changed to bbbbbu by policy - memname stmt#Step REGION ABOVE changed to mmmmmu by policy - memname stmt#Step SYSTEM RESERVED BELOW set to xxxxxu by policy - memname stmt#Step SYSTEM RESERVED ABOVE set to yyyyyu by policy - memname stmt#Step MEMLIMIT set to zzzzzu by policy - memname stmt#Step data space number limit set to nnnnnnnnnn by policy - memname stmt#Step data shared page limit set to ssssssssss by policy - memname stmt#Step data space size limit set to dddddu by policy - memname stmt#Step DEDICATED MEMORY changed to (nnnnn{G|T|P}, mmmmm{G|T|P}) by policy - memname stmt#Step canceled due to insufficient DEDICATED MEMORY value (nnnnn {G|T|P},mmmmm{G|T|P})- memname stmt#",
	"IEF044I": "Actions ignored by SMFLIMxx parmlib policy for jobname stepnameStep region below ignored by policy - memname stmt#Step region above ignored by policy - memname stmt#Step region reserved below ignored by policy - memname stmt#Step region reserved above ignored by policy - memname stmt#",
	"IEF083I": "UNIDENTIFIED PARAMETER IN THE parameter FIELD",
	"IEF085I": "REGION UNAVAILABLE, ERROR CODE=cde",
	"IEF086I": "ERROR IN SWA RECOVERY - RESTART CANCELLED. REASON CODE = reason-code",
	"IEF087I": "ERROR ON JOB JOURNAL - RESTART CANCELLED. REASON CODE = reason-code",
	"IEF089I": "ERROR ON WRITE TO JOB JOURNAL-JOB NOT ELIGIBLE FOR RESTART.",
	"IEF090E": "PROTECT KEY UNAVAILABLE jobname PLACED ON HOLDQ",
	"IEF091I": "PROTECT KEY UNAVAILABLE START ppp REJECTED",
	"IEF092I": "jobname [procstep] stepname WAITING FOR xxxK REAL STORAGE",
	"IEF093I": "INITIATOR TERMINATED DUE TO REGION LOSS location",
	"IEF094A": "INITIATOR TERMINATED DUE TO REGION LOSS location, RESTART INITIATOR",
	"IEF097I": "jobname USER userid ASSIGNED",
	"IEF098I": "SCHEDxx LINE num: PPT STMT IGNORED. NO OPERANDS SPECIFIED.",
	"IEF099I": "JOB jobname WAITING FOR DATA SETS",
	"IEF100I": "text1 [text2] ABEND=cde[,REASON=rrrrr]",
	"IEF101I": "jobname [procstep] stepname STEP FAILED, UNABLE TO RESOLVE UNIT AFFINITY, REASON reason-code",
	"IEF102I": "jobname [procstep] stepname ddname [+ xxx] - UNRECOVERABLE DADSM ERROR OCCURRED",
	"IEF103I": "jobname [procstep] stepname ddname [+ xxx] - UNKNOWN DADSM ERROR RETURN CODE - nnnn",
	"IEF104I": "UNIT dev NOT BROUGHT ONLINE",
	"IEF105I": "jobname [procstep] stepname ddname callername UNKNOWN ERROR DURING LOGICAL PARMLIB SERVICE PROCESSING.",
	"IEF106I": "jobname - UNIT dev BROUGHT ONLINE NAME=name CODE=code [text]...",
	"IEF107I": "PARMLIB CONCATENATION WAS UPDATED FROM loadxx",
	"IEF108I": "jobname [procstep] stepname callername READ BUFFER INPUT TO LOGICAL PARMLIB SERVICE HAS INVALID FORMAT.",
	"IEF109I": "PARMLIB CONCATENATION WAS NOT UPDATED FROM loadxx. reason",
	"IEF110I": "UNIT dddd DEALLOCATED BY SYSTEM DURING VARY OFFLINE PROCESSING BECAUSE NO ALLOCATED ASID WAS FOUND",
	"IEF111I": "jobname [procstep] stepname ddname [ + xxx ] ALLOCATION FAILED - DEVICE dev IS NOT IN LIBRARY library",
	"IEF112I": "jobname [procstep] stepname ddname [ + xxx ] UNABLE TO ALLOCATE UNITS TO ONE GENERIC. REQUESTED ddd1, STILL NEEDED ddd2",
	"IEF113I": "jobname [procstep] stepname ddname [ + xxx ] ALLOCATION FAILED - A LIBRARY REQUEST SPECIFIED A NON-LIBRARY DEVICE dev",
	"IEF114I": "DEVICE POOLS devpool-list",
	"IEF115I": "jobname [procstep] stepname ddname [+ xxx] ALLOCATION FAILED - ddd UNITS REQUIRED, BUT NO LIBRARY HAS ENOUGH UNITS",
	"IEF116I": "jobname stepname MOUNT OF VOLUME ser ON DEVICE dev FAILED",
	"IEF118I": "jobname stepname MOUNT OF VOLUME ser ON DEVICE dev FAILED",
	"IEF119I": "ERROR VERIFYING INTERNAL VOLUME LABEL ser ON DEVICE dev",
	"IEF120I": "jobname [procstep] stepname ddname [+ xxx] ALLOCATION FAILED - A NON-LIBRARY REQUEST SPECIFIED A LIBRARY DEVICE dev",
	"IEF121I": "ALLOCATION QUEUE CHAIN ERROR DETECTED AND REPAIRED",
	"IEF121A": "CRITICAL ALLOCATION QUEUE CHAIN ERROR DETECTED",
	"IEF122I": "jobname [procstep] stepname ddname [+ xxx] SMS DETECTED AN ERROR DURING DATA SET STACKING.",
	"IEF123I": "jobname [procstep] stepname ddname [+ xxx] SMS DETECTED AN ERROR DURING DEVICE POOL SERVICES PROCESSING.",
	"IEF124I": "jobname [procstep] stepname ddname [+ xxx] ALLOCATION FAILED - DEVICE POOL dpoolnam COULD NOT BE FOUND IN THE ACTIVE EDT",
	"IEF125I": "userid-LOGGED ON [-TIME=hh.mm.ss]",
	"IEF126I": "userid-LOGGED OFF [-TIME=hh.mm.ss]",
	"IEF127I": "jobname [procstep] stepname ddname[+ xxx] - NO SPACE PARAMETER OR ZERO SPACE REQUEST AT ABSTR ZERO",
	"IEF128I": "jobname [procstep] stepname ddname[+ xxx] - INVALID REQUEST FOR ISAM INDEX",
	"IEF129I": "jobname [procstep] stepname ddname[+ xxx] - MULTIVOLUME INDEX NOT ALLOWED",
	"IEF130I": "jobname [procstep] stepname ddname[+ xxx] - DSNAME ELEMENT WRONG - MUST BE INDEX, OVFLOW, OR PRIME",
	"IEF131I": "jobname [procstep] stepname ddname[+ xxx] - MULTIVOLUME OVFLOW REQUEST NOT ALLOWED",
	"IEF132I": "jobname [procstep] stepname ddname[+ xxx] - SPACE PARAMETER WRONG - CYL AND ABSTR CONFLICT",
	"IEF133I": "jobname [procstep] stepname ddname[+ xxx] - SPACE PARAMETER WRONG - CYL AND CONTIG CONFLICT",
	"IEF134I": "jobname [procstep] stepname ddname[+ xxx] - SUBPARAMETER WRONG IN SPACE PARAMETER - MUST BE CYL OR ABSTR",
	"IEF135I": "jobname [procstep] stepname ddname[+ xxx] - PRIMARY SPACE REQUEST MAY NOT BE ZERO",
	"IEF136I": "jobname [procstep] stepname ddname[+ xxx] - DUPLICATION IN ALLOCATION - INDEX AREA REQUESTED TWICE",
	"IEF140I": "jobname [procstep] stepname ddname[+ xxx] - DIRECTORY SPACE REQUEST LARGER THAN AMOUNT AVAILABLE ON THIS VOLUME",
	"IEF141I": "jobname [procstep] stepname ddname[+ xxx] - INDEX REQUEST MUST PRECEDE PRIME FOR ISAM DATA SET",
	"IEF142I": "jobname [procstep] stepname STEP WAS EXECUTED - COND CODE cde",
	"IEF143I": "jobname [procstep] stepname ddname[+ xxx] - LAST CONCATENATED DD STATEMENT UNNECESSARY OR INVALID FOR THIS DATA SET",
	"IEF145I": "jobname [procstep] stepname ddname[+ xxx] - SPACE REQUEST MUST BE ABSTR FOR DOS VOLUME",
	"IEF147I": "jobname [procstep] stepname ddname [xxx] ALLOCATION FAILED - NO DEVICE POOLS AVAILABLE FOR ALLOCATION",
	"IEF148I": "jobname [procstep] stepname ddname [xxx] ALLOCATION FAILED - REQUESTED DEVICE IS MARKED UNAVAILABLE",
	"IEF150I": "jobname [procstep] stepname ddname [xxx] ALLOCATION FAILED - UNABLE TO OBTAIN VOLUME RECORD FOR VOLUME ser",
	"IEF151I": "jobname [procstep] stepname ddname [+ xxx] ALLOCATION FAILED - NON-LIBRARY REQUEST NEEDS VOLUME ser FROM LIBRARY libname",
	"IEF152I": "jobname [procstep] stepname ddname [+ xxx] ALLOCATION FAILED - NON-LIBRARY VOLUME ser REQUIRED IN LIBRARY libname",
	"IEF153I": "jobname [procstep] stepname ddname [+ xxx] ALLOCATION FAILED - LIBRARY libname1 VOLUME ser NEEDED IN LIBRARY libname2",
	"IEF154I": "jobname stepname CANNOT BRING DEVICES ONLINE IN LIBRARY libname BECAUSE LIBRARY IS OFFLINE",
	"IEF155I": "jobname [procstep] stepname ddnamexx [+ xxx] ALLOCATION FAILED - UNABLE TO OBTAIN LIBRARY ID FOR DEVICE dev",
	"IEF156I": "jobname [procstep] stepname ddnamexx [+ xxx] ALLOCATION FAILED - UNABLE TO OBTAIN LIBRARY STATUS FOR LIBRARY libname",
	"IEF157E": "jobname [procstep] stepname ddname [+ xxx ] NEEDS ddd UNIT(S) [[FOR VOLUME(S): ser, [ser, [,...,ser]][SCRTCH-nnn] [PRIVAT-nnn]]| [LIBRARY: libname LIBRARY STATUS: status]]ALL ELIGIBLE UNITS ARE CURRENTLY ALLOCATED",
	"IEF167I": "NO JOB JOURNAL OPTION SPECIFIED - RESTART CANCELLED",
	"IEF168I": "ERROR ON JOB JOURNAL - RESTART FOR JOB CANCELLED",
	"IEF169I": "RESTART CANCELLED FOR JOB jobname",
	"IEF170I": "n jobname message",
	"IEF172E": "jobname HELD, CPU (x) OFFLINE OR UNAVAILABLE FOR JOB SCHEDULING",
	"IEF173I": "jobname FAILED, CPU (x) OFFLINE OR UNAVAILABLE FOR JOB SCHEDULING",
	"IEF174I": "SYSTEM ERROR BEFORE JOB INITIATION",
	"IEF175I": "AMP KEY WORD keyword DUPLICATE OR CONFLICTING PARM STEP NOT EXECUTED",
	"IEF176I": "WTR jobname WAITING FOR WORK, {CLASS= | FORMS= | WRITER= | DEST= | JOBID=}",
	"IEF177I": "WTR jobname INVALID MODIFY KEY WORD",
	"IEF179I": "WTR jobname INVALID {JOBID jjjjjjjj|DEST xxxxxx}",
	"IEF180I": "jobname [procstep] stepname - INSUFFICIENT REAL OR VIRTUAL STORAGE FOR ALLOCATION",
	"IEF186I": "REGION UNAVAILABLE FOR RESTART, ERROR CODE=cde",
	"IEF187I": "jobname FAILED - SYSTEM ERROR IN INITIATOR",
	"IEF188I": "PROBLEM PROGRAM ATTRIBUTES ASSIGNED",
	"IEF191I": "RESTART CANCELLED FOR JOB jobname - NO FURTHER STEPS TO BE EXECUTED",
	"IEF192I": "jobname [procstep] stepname ddname[+ xxx] - NO ELIGIBLE DEVICE TYPE CONTAINS ENOUGH UNITS TO SATISFY REQUEST",
	"IEF193I": "jobname [procstep] stepname ddname[+ xxx] - SPACE NOT OBTAINED BECAUSE OF PERMANENT I/O ERROR",
	"IEF194I": "jobname [procstep] stepname ddname[+ xxx] - VOLUME SEQUENCE NUMBER EXCEEDS NUMBER OF VOLUME SERIALS",
	"IEF195I": "jobname [procstep] stepname ddname[+ xxx] - MAXIMUM NUMBER OF DEVICES FOR DD EXCEEDED",
	"IEF196I": "text",
	"IEF197I": "SYSTEM ERROR DURING {ALLOCATION|UNALLOCATION}",
	"IEF198I": "jobname [procstep] stepname ddname [+ xxx] - INSUFFICIENT UNRESTRICTED UNITS ELIGIBLE TO SATISFY REQUEST",
	"IEF199I": "jobname [procstep] stepname - CATALOG NOT MOUNTED - VOLUME MOUNTING NOT ALLOWED",
	"IEF201I": "jobname [procstep] stepname - JOB TERMINATED BECAUSE OF CONDITION CODES",
	"IEF202I": "jobname [procstep] stepname - STEP WAS NOT RUN BECAUSE OF {CONDITION CODES|COND=ONLY}",
	"IEF206I": "jobname [procstep] stepname - STEP WAS NOT RUN BECAUSE OF CONDITIONAL EXPRESSION ON STATEMENT xxxx",
	"IEF209I": "VIRTUAL STORAGE UNAVAILABLE FORjobname.procstep.stepname",
	"IEF210I": "jobname [procstep] stepname ddname[+ xxx] - UNIT FIELD SPECIFIES INCORRECT DEVICE NAME",
	"IEF211I": "jobname [procstep] stepname ddname[+ xxx] - DATA SET RESERVATION UNSUCCESSFUL",
	"IEF212I": "jobname [procstep] stepname ddname[+ xxx] - DATA SET NOT FOUND",
	"IEF213I": "jobname [procstep] stepname ddname[+ xxx] - UNDETERMINED ERROR PROCESSING CATALOGED DATA SET",
	"IEF214I": "jobname [procstep] stepname ddname[+ xxx] - UNDETERMINED ERROR PROCESSING MIGRATED DATA SET",
	"IEF217I": "jobname [procstep] stepname ddname[+ xxx] - VOLUME CONTAINING PATTERN DSCB NOT MOUNTED",
	"IEF218I": "jobname [procstep] stepname ddname[+ xxx] - PATTERN DSCB RECORD NOT FOUND IN VTOC",
	"IEF219I": "jobname [procstep] stepname ddname[+ xxx] - GDG GROUP NAME EXCEEDS 35 CHARACTERS",
	"IEF220I": "jobname [procstep] stepname ddname[+ xxx] - GDG DEFINITION NOT VALID - VSAM DATA SET NOT SUPPORTED",
	"IEF221I": "jobname [procstep] stepname - PGM=*.DD - REFERENCED STEP WAS NOT EXECUTED - OR DATA SET TYPE INVALID",
	"IEF222I": "ALLOCxx LINE yyyy: ERROR IN tttt STATEMENT, {KEYWORD kkkk.} REASON=reason-code",
	"IEF223I": "ERROR(S) IN ALLOCxx PARMLIB MEMBER(S), REFER TO HARDCOPY LOG",
	"IEF225D": "SHOULD jobname.procstep.stepname [checkidd] RESTART",
	"IEF229I": "LRECL EXCEEDS 32K",
	"IEF230I": "THE ATS WORK TASK IEFHTSWT ABENDED AND WAS REATTACHED",
	"IEF233A": "M dev,ser,[labtyp], jobname [,stepname [,dsname [,mediatype [,storgrp]]]]",
	"IEF233D": "M dev,ser,[labtyp],jobname [,stepname [,dsname [,mediatype [,storgrp]]]], OR RESPOND TO IEF455D MESSAGE",
	"IEF234E": "text1. dev [,ser, text2, jobname[,stepname]] [,SPACE=cpcc,tttt,aaaa/yyyy,zzzz]",
	"IEF235D": "jobname stepname WAITING FOR VOLUMES, TO CANCEL WAIT REPLY ‘NO’",
	"IEF236I": "ALLOC. FOR jobname [procstep] stepname",
	"IEF237I": "dev ALLOCATED TO ddname",
	"IEF238D": "jobname - REPLY [DEVICE NAME] [,] [‘WAIT’] OR ‘CANCEL’",
	"IEF240I": "jobname [procstep] stepname - TASK I/O TABLE EXCEEDS TIOT LIMIT OF xxxxK",
	"IEF242I": "ALLOC. FOR jobname [procstep] stepname AT ABEND",
	"IEF244I": "jobname [procstep] stepname - UNABLE TO ALLOCATE nnn UNIT(S) text",
	"IEF245I": "jobname [procstep] stepname ddname[+ xxx] - INCONSISTENT UNIT NAME AND VOLUME SERIAL",
	"IEF246I": "jobname [procstep] stepname ddname[+ xxx] - INSUFFICIENT SPACE ON STORAGE VOLUMES",
	"IEF251I": "jobname [procstep] stepname - JOB CANCELLED (in SYSOUT) --or-- jobname JOB CANCELLED (on console)",
	"IEF253I": "jobname [procstep] stepname ddname[+ xxx] - DUPLICATE NAME ON DIRECT ACCESS VOLUME",
	"IEF254I": "jobname [procstep] stepname ddname[+ xxx] - NO SPACE IN VTOC OR VTOC INDEX",
	"IEF256I": "jobname [procstep] stepname ddname[+ xxx] - ABSOLUTE TRACK NOT AVAILABLE",
	"IEF257I": "jobname [procstep] stepname ddname[+ xxx] - SPACE REQUESTED NOT AVAILABLE",
	"IEF258I": "jobname [procstep] stepname ddname[+ xxx] - INVALID RECORD LENGTH SPECIFIED IN SPACE PARAMETER",
	"IEF259I": "UNIT devnum IS NO LONGER DEFINED AS AUTOSWITCH.",
	"IEF260I": "jobname [procstep] stepname ddname[+ xxx] - WRONG DSORG OR DISP",
	"IEF261I": "jobname [procstep] stepname ddname[+ xxx] - NO PRIME AREA REQUEST FOR ISAM DATA SET",
	"IEF262I": "jobname [procstep] stepname ddname[+ xxx] - PRIME AREA MUST BE REQUESTED BEFORE OVFLOW",
	"IEF263I": "jobname [procstep] stepname ddname[+ xxx] - SPACE REQUEST WRONG - MUST BE ON CYLINDER BOUNDARY",
	"IEF264I": "jobname [procstep] stepname ddname[+ xxx] - DUPLICATION OF THE DSNAME ELEMENT INVALID - SAME AREA REQUESTED TWICE",
	"IEF266I": "jobname [procstep] stepname ddname[+ xxx] - INVALID JFCB POINTER",
	"IEF267I": "jobname [procstep] stepname ddname[+ xxx] - DIRECTORY SPACE REQUEST IS LARGER THAN PRIMARY REQUEST",
	"IEF272I": "jobname [procstep] stepname - STEP WAS NOT EXECUTED",
	"IEF273I": "jobname [procstep] stepname ddname[+ xxx] - INVALID USER LABEL REQUEST",
	"IEF274I": "jobname [procstep] stepname ddname[+ xxx] - SPACE REQUEST REJECTED BY INSTALLATION EXIT, REASON CODE nnnn",
	"IEF275I": "jobname [procstep] stepname ddname[+ xxx] - SPACE REQUEST CANNOT BE SATISFIED, INSTALLATION EXIT REASON CODE nnnn",
	"IEF278I": "jobname {procstep} stepname ddname {+ xxx} UNIT AFFINITY IGNORED, REASON reason-code, ALLOCATED USING unitname.",
	"IEF280I": "jobname {procstep} stepname STEP FAILED, UNABLE TO RESOLVE INCONSISTENT DEVICE CATEGORIES BETWEEN ddname1, ddname2",
	"IEF281I": "dev NOW OFFLINE [-DEVICE IS BOXED]",
	"IEF282I": "dev NOW UNLOADED [ -DEVICE IS BOXED]",
	"IEF283I": "dsname {NOT DELETED rc | UNCATALOGED} VOL SER NOS= ser [z],ser [z],ser [z],ser [z],ser [z] VOL SER NOS= ser [z],ser [z],ser [z].",
	"IEF284I": "jobname stepname procname ddname +relpos UNABLE TO ALLOCATE - DEVICE devnum IS ASSIGNED TO A FOREIGN HOST",
	"IEF285I": "dsname dsp rc VOL SER NOS= ser,ser,ser,ser,ser VOL SER NOS= ser,ser,ser.",
	"IEF286I": "jobname [procstep] stepname ddname[+ xxx] - DISP FIELD INCOMPATIBLE WITH DSNAME",
	"IEF287I": "dsname dsp w VOL SER NOS= ser,ser,ser,ser,ser VOL SER NOS= ser,ser,ser.",
	"IEF288I": "dsname SYSOUT",
	"IEF289E": "jobname stepname WAITING FOR VOLUME(S) OR UNIT(S)",
	"IEF291I": "jobname stepname HAS RECEIVED AN INVALID ACTION CODE xxx FROM yyy USER EXIT",
	"IEF292I": "UNIT devnum IS ASSIGNED TO A FOREIGN HOST",
	"IEF293I": "UNIT dev NOT VARIED ONLINE, UNABLE TO REGISTER DEVICE. SAME NED ASdupdev",
	"IEF294I": "UNIT devnum IS NO LONGER ASSIGNED TO A FOREIGN HOST",
	"IEF295I": "jobname [procstep] stepname ddname [+ xxx] — VOLUME MOUNTING NOT ALLOWED BUT IS NEEDED BY JES3 INITIALIZATION",
	"IEF300I": "jobname WTR CLOSED - SUBSYSTEM INTERFACE ERROR xxxx/yyyy",
	"IEF301I": "jobname WTR CLOSED",
	"IEF302A": "jobname WTR WAITING TO START aaaaaaaa FOR JOBID nnnnnnnn",
	"IEF303I": "jobname WTR CLOSED - OUTPUT ERROR",
	"IEF307I": "jobname WTR CLOSED-OUTPUT DCB FAILED TO OPEN",
	"IEF311I": "NOP - SETPRT PARAMETER LIST INVALID",
	"IEF314I": "SYSIO",
	"IEF316I": "CCBAD",
	"IEF318I": "jobname [procstep] stepname ddname[+ xxx] ‘UNIT=AFF’ INVALID FOR REQUEST SPECIFYING NEW DIRECT ACCESS DATA SET",
	"IEF321I": "INVALID SEGMENT",
	"IEF322I": "NO FCB IMAGE-ID SPECIFIED FOR VERIFICATION",
	"IEF323I": "NO FCB IMAGE-ID SPECIFIED FOR ALIGNMENT",
	"IEF324I": "NO UCS IMAGE-ID SPECIFIED FOR VERIFICATION",
	"IEF325I": "OPERATOR CANCELLED LOAD. UCS/FCB IMAGE-ID/CHAIN NOT AVAILABLE.",
	"IEF326I": "PERMANENT I/O ERROR ON BLDL LOCATE ON UCS/FCB IMAGE IN SYSTEM LIBRARY",
	"IEF327I": "WTR dev CLOSED. PERMANENT I/O ERROR WHILE LOADING UCS/FCB BUFFER",
	"IEF328I": "WTR dev CLOSED. PERMANENT I/O ERROR ON UCS/FCB IMAGE VERIFICATION.",
	"IEF329I": "WTR dev CLOSED. OPERATOR CANCELLED LOAD. INCORRECT UCS/FCB IMAGE DISPLAYED FOR VERIFICATION.",
	"IEF330I": "jobname [procstep] stepname ddname[+ xxx] - DATA SET WAIT REQUEST CANCELLED",
	"IEF331I": "WTR dev CLOSED. SETPRT NOP-UNCORRECTABLE OUTPUT ERROR ON PREVIOUS OPERATION.",
	"IEF333I": "jobname [procstep] stepname ddnamexx [+ xxx ] UNABLE TO ALLOCATE UNITS TO ONE LIBRARY. REQUESTED ddd1 STILL NEEDED ddd2",
	"IEF336I": "jobname [procstep] stepname ddname [+ xxx] JOB CANCELLED BY {|VOLUME_MNT |SPEC_WAIT|ALLC_OFFLN} INSTALLATION {POLICY|EXIT}",
	"IEF337I": "jobname [procstep] stepname - UNABLE TO ACCESS LOCKED CATALOG",
	"IEF341I": "ALLOCATION LISTEN REQUEST FAILED. VARYING A DEVICE ONLINE WILL NOT START WAITING JOBS.",
	"IEF343I": "jobname [procstep] stepname - ddname[+ xxx] REQUEST FAILED - text",
	"IEF344I": "jobname [procstep] stepname - ddname [+ xxx] ALLOCATION FAILED DUE TO DATA FACILITY SYSTEM ERROR",
	"IEF345I": "jobname [procstep] stepname - ddname [+ xxx] ALLOCATION FAILED DUE TO SCHEDULER JCL FACILITY ERROR.",
	"IEF347I": "jobname [procstep] stepname - ddname [+ xxx] DEVICE - dev CANNOT BE ALLOCATED - IMPROPER AUTHORIZATION",
	"IEF348I": "AUTOSWITCH DEVICE dddd WILL NOT BE CONSIDERED FOR THIS ALLOCATION DUE TO AN I/O ERROR DURING ASSIGN PROCESSING",
	"IEF350I": "CHECKPOINT OF JOB jobname STEP stepname.procstep ABENDED Sabn REASON=rrc",
	"IEF351I": "ASSIGN PROCESSING TIMED OUT FOR AUTOSWITCH DEVICE dddd",
	"IEF352I": "ADDRESS SPACE UNAVAILABLE",
	"IEF353A": "INITIATOR TERMINATED DUE TO CROSS MEMORY BIND, RESTART INITIATOR",
	"IEF354I": "DISABLED DASD DEVICE dev NOT VARIED ONLINE",
	"IEF355A": "INITIATOR TERMINATED, RESTART INITIATOR",
	"IEF356I": "ADDRESS SPACE TERMINATED DUE TO CROSS MEMORY BIND",
	"IEF357I": "jobname[procstep] stepname ddname [xxx] ALLOCATION FAILED - UNABLE TO OBTAIN LIBRARY RECORD FOR LIBRARY library",
	"IEF358I": "jobname [procstep] stepname ddname(+xxx) - TP DEVICE dev NOT ALLOCATED, DEVICE DELETED FROM I/O CONFIGURATION.",
	"IEF359I": "RESERVED OR BROKEN DASD DEVICE dev NOT VARIED ONLINE",
	"IEF360I": "RESTART NOT SUCCESSFUL FOR jobname: ERROR IN SAF",
	"IEF361I": "jobname [procstep] stepname - UNABLE TO ALLOCATE/OPEN PRIVATE CATALOG OR ALLOCATE CVOL",
	"IEF362I": "jobname [procstep] stepname - UNABLE TO CLOSE/UNALLOCATE PRIVATE CATALOG OR UNALLOCATE CVOL",
	"IEF363I": "jobname [procstep] stepname - INSUFFICIENT REAL OR VIRTUAL STORAGE FOR PROCESSING CATALOGED DATA SET",
	"IEF364I": "jobname [procstep] stepname - PERMANENT I/O ERROR PROCESSING CATALOGED DATA SET",
	"IEF365I": "jobname [procstep] stepname ddname[+ xxx] - INVALID REFERENCE TO A GENERATION DATA GROUP NAME",
	"IEF366I": "jobname [procstep] stepname ddname[+ xxx] - RELATIVE GENERATION NUMBER SPECIFIED FOR GDG CONTAINS SYNTAX ERROR",
	"IEF367I": "jobname [procstep] stepname - I/O ERROR OBTAINING PATTERN DSCB",
	"IEF368I": "jobname [procstep] stepname - UNABLE TO function CATALOG - RETURN INFOrc CATALOG NAME: dsname",
	"IEF369D": "jobname,stepname INVALID REPLY - MOUNT VOLUME OR REPLY ‘NO’",
	"IEF371I": "- jobname [procstep] stepname ddname [+ xxx] - TELECOMMUNICATION DEVICE NOT ACCESSIBLE",
	"IEF372I": "jobname [procstep] stepname ddname[+ xxx] - VOLUME FIELD CONTAINS REFERENCE TO A DD NOT PREVIOUSLY RESOLVED",
	"IEF373I": "STEP/stepname/START yyyyddd.hhmm",
	"IEF374I": "STEP/stepname/STOP yyyyddd.hhmm CPU xxxx MIN xx.xx SECSRB xxxx MIN xx.xx SECREAL/VIRT xxxxK  SYS xxxxKEXT xxxxK  SYS xxxxK",
	"IEF375I": "JOB/jobname/START yyyyddd.hhmm",
	"IEF376I": "JOB/jobname/STOP yyyyddd.hhmm CPU xxxx MIN xx.xx SEC SRB xxxx MIN xx.xx SEC",
	"IEF377I": "jobname [procstep] stepname dsname NOT disp w",
	"IEF378I": "jobname [procstep] stepname - JOB FAILED [ - TIME= hh.mm.ss] CATALOG DISPOSITION ERROR",
	"IEF379I": "jobname [procstep] stepname - JOB ENDED BECAUSE OF CATALOG ERROR",
	"IEF380I": "jobname [procstep] stepname ddname [+ xxx] - VOLUME COUNT FOR DD EXCEEDED: SPECIFIC-xxx NON-SPECIFIC-yyy",
	"IEF381I": "DEVICE dev HAS NO UNIT NAME, DEVICE TYPE IS 'dddddddd'X",
	"IEF382A": "jobname WTR WAIT DUE TO PAUSE",
	"IEF383A": "jobname WTR, CHANGE FORM TO nnnn",
	"IEF384I": "jobname [procstep] stepname ddname - WARNING: VOLUME NOT RETRIEVED FROM CATALOG",
	"IEF386I": "hh.mm.ss DISPLAY PPT [No Values Matching: mtchname] [ {No Parmlib Values} {Parmlib Values} {Parmlib Values Matching: mtchname} PgmName  NC NS PR ST ND BP Key 2P 1P NP NH CP entrynam     x   x   x   x   x  x   k   x  x   x   x   x] [ {No Default Values} {Default Values} {Default Values Matching: mtchname} PgmName  NC NS PR ST ND BP Key 2P 1P NP NH CP entrynam     x   x   x   x   x  x   k   x  x   x   x   x ] [ ReferenceSynonym   ---Meaning-----------------------   --------SCHEDxx keyword-----------     NC     Non-cancelable                       NOCANCEL    NS     Non-swappable                       NOSWAP    PR      Privileged                           PRIV    ST      System task                         SYST    ND     No dataset integrity                  NODSI    BP      Bypass password protection          NOPASS    Key     PSW key for this program           KEY(x)    2P      Second level preferred storage        SPREF    1P      First level preferred storage           LPREF    NP     No preferred storage                  NOPREF    NH     No honor IEFUSI region settings     NOHONORIEFUSIREGION    CP     Critical paging                       CRITICALPAGING ]",
	"IEF391I": "jobname stepname procname ddname +relpos UNABLE TO ALLOCATE - A TAPE ALLOCATION SUBSYSTEM ELIMINATED ELIGIBLE DEVICES",
	"IEF396I": "ERROR DETECTED BY THE INITIATOR, SYMPTOM CODES = xx,yyyy,zzzzzzzz.",
	"IEF402I": "{jobname|cm| stc_procname.identifier} FAILED IN ADDRESS SPACE asid SYSTEM ABEND Scde - REASON CODE rc",
	"IEF403I": "jobname-STARTED [-TIME=hh.mm.ss]",
	"IEF404I": "jobname-ENDED [-TIME=hh.mm.ss]",
	"IEF405I": "jjobname .procstep. stepname ddname dsname WARNING: 2-DIGIT EXPDT",
	"IEF406I": "jjobname .procstep. stepname ddname dsname APPLICATION FAILED: 2-DIGIT EXPDT",
	"IEF414I": "dev UNIT NOT AVAILABLE - UNLOAD ATTEMPTED",
	"IEF415I": "dev NOT UNLOADED - NO LONGER PENDING UNLOAD",
	"IEF420I": "MVS DEFAULT MODE CONTROL FAILURE, DEVICE dev NOT ASSIGNED",
	"IEF428I": "WARNING: 2-DIGIT EXPIRATION DATE USED",
	"IEF429I": "ALLOCATION FAILED: 2-DIGIT EXPIRATION DATE USED IN THE EXPDT SUBPARAMETER OF THE LABEL FIELD",
	"IEF430I": "RESTART STEP NOT FOUND FOR JOB jobname",
	"IEF431E": "ZERO QMPA POINTER FOUND. SWA MANAGER REASON CODE=3C",
	"IEF433D": "jobname - WAIT REQUESTED -- REPLY ‘HOLD’ OR ‘NOHOLD’",
	"IEF434D": "jobname - INVALID REPLY. REPLY ‘HOLD’ OR ‘NOHOLD’",
	"IEF438I": "SUBTASK OF jobname TERMINATED. COMPLETION CODE cde",
	"IEF447I": "AMP KEY WORD keywd IS INVALID STEP WAS NOT EXECUTED",
	"IEF448I": "AMP KEY WORD keywd VALUE val IS TOO LARGE STEP NOT EXECUTED",
	"IEF449I": "AMP KEY WORD keywd REQUIRES A DECIMAL VALUE STEP NOT EXECUTED",
	"IEF450I": "jobname [procstep] stepname - ABEND {Scde | Ucde} REASON=xxxxxxxx [TIME=hh.mm.ss]",
	"IEF451I": "jobname [procstep] stepname - ENDED BY CC cde[-TIME=hh.mm.ss]",
	"IEF452I": "jobname - JOB NOT RUN - JCL ERROR [- TIME=hh.mm.ss]",
	"IEF453I": "jobname - JOB FAILED - JCL ERROR [- TIME=hh.mm.ss]",
	"IEF455D": "MOUNT ser ON dev FOR jobname stepname OR REPLY ‘NO’",
	"IEF456I": "jobname [procstep] stepname - DEVICE ALLOCATION UNABLE TO ESTABLISH ESTAE ENVIRONMENT",
	"IEF458D": "jobname stepname WAITING FOR DATASET. TO CANCEL WAIT REPLY ‘NO’",
	"IEF462I": "jobname [procstep] stepname ddname[+ xxx] - NO AVAILABLE OFFLINE DEVICES ELIGIBLE FOR ALLOCATION",
	"IEF463I": "jobname [procstep] stepname ddname[+ xxx] - UNABLE TO ALLOCATE SUBSYSTEM DATA SET",
	"IEF464I": "jobname [procstep] stepname ddname[+ xxx] - DEVICE IS BOXED - CANNOT BE ALLOCATED",
	"IEF465I": "jobname [procstep] stepname - UNABLE TO ALLOCATE SUBSYSTEM DATA SET",
	"IEF466I": "jobname [procstep] stepname ddname[+ xxx] - UNABLE TO RECOVER FROM DADSM FAILURE",
	"IEF467I": "jobname [procstep] stepname ddname[+ xxx] - UNITS REQUIRED NOT CURRENTLY AVAILABLE - WAITING NOT ALLOWED",
	"IEF468I": "jobname [procstep] stepname - INSUFFICIENT REAL OR VIRTUAL STORAGE FOR UNALLOCATION",
	"IEF469I": "jobname [procstep] stepname DATA SETS HAVE NOT BEEN RELEASED",
	"IEF470I": "jobname [procstep] stepname - UNALLOCATION FAILED",
	"IEF471E": "FOLLOWING VOLUMES NO LONGER NEEDED BY jobname ser,ser,...ser",
	"IEF472I": "jobname [procstep] stepname - COMPLETION CODE - SYSTEM=Scde USER=Ucde REASON=xxxxxxxx",
	"IEF473I": "jobname [procstep] stepname - ERROR ATTEMPTING TO SELECT OPTIMUM DEVICE FOR ALLOCATION OF ddname [+ xxx]",
	"IEF474I": "jobname [procstep] stepname ddname[+ xxx] - UNIT OR VOLUME IN USE BY SYSTEM FUNCTION - CANNOT BE ALLOCATED",
	"IEF475I": "jobname [procstep] stepname ddname[+ xxx] - VOL ON INELIGIBLE PERMRES OR RSVD UNIT",
	"IEF476I": "jobname [procstep] stepname ddname[+ xxx] - OVERLAPPING DATA SETS IN VTOC",
	"IEF477I": "jobname [procstep] stepname ddname[+ xxx] - OVERLAPPING DOS SPLIT CYLINDER DATA SETS IN VTOC",
	"IEF478I": "jobname [procstep] stepname ddname[+ xxx] - VTOC ERROR MAY EXIST - ANALYZE VTOC LISTING",
	"IEF479I": "jobname [procstep] stepname ddname[+ xxx] - POSSIBLE VTOC ERROR ON 2ND OR LATER VOLUME OF ISAM PRIME DATA SET",
	"IEF480I": "jobname [procstep] stepname ddname[+ xxx] - INVALID DESTINATION REQUESTED",
	"IEF481I": "jobname [procstep] stepname ddname[+ xxx] - SAME UNIT REQUESTED TWICE - CONFLICTS EXIST",
	"IEF482I": "jobname [procstep] stepname ddname[+ xxx] - PERMRES/RESRV VOLUME ON REQUIRED UNIT",
	"IEF483I": "jobname [procstep] stepname ddname[+ xxx] - REQUESTED DEVICE IS A CONSOLE",
	"IEF484I": "jobname [procstep] stepname ddname[+ xxx] - MORE UNITS REQUIRED FOR REQUEST",
	"IEF485I": "jobname [procstep] stepname [ddname] - VOLUMES REQUIRED NOT CURRENTLY AVAILABLE - WAITING NOT ALLOWED",
	"IEF488I": "jobname - ddname +nnn MUST WAIT FOR [UNIT dev|VOLUME ser ON UNIT dev]",
	"IEF490I": "jobname - INVALID REPLY. [text]",
	"IEF491I": "jobname [procstep] stepname - DD GENERATIONS CAUSE TOTAL DD STATEMENTS TO EXCEED TIOT LIMIT OF xxxxK",
	"IEF492I": "jobname [procstep] stepname ddname[+ xxx] - INVALID DATA SET NAME SPECIFIED ON JOBCAT OR STEPCAT STATEMENT",
	"IEF493I": "jobname [procstep] stepname ddname[+ xxx] - INVALID PARAMETERS SPECIFIED FOR JOBCAT OR STEPCAT",
	"IEF500I": "ddtype DD ddname IS ERRONEOUSLY MARKED AS AN SMS LIBRARY MANAGED TAPE REQUEST",
	"IEF502I": "text",
	"IEF503I": "{UNIT dev INCORRECT VOLUME LABEL | UNIT dev I/O ERROR}",
	"IEF506I": "jobname [procstep] stepname ddname[+ xxx] - NO STORAGE VOLUMES. ‘VOLUME=PRIVATE’ ASSUMED.",
	"IEF510I": "VOLUME HAS ANS LABEL",
	"IEF524I": "dev{, VOLUME ser} PENDING OFFLINE",
	"IEF525E": "dev{, VOLUME ser} STILL PENDING OFFLINE",
	"IEF550I": "jobname {procstep} stepname STEP FAILED, UNABLE TO RESOLVE DATA SET STACKING, REASON reason-code",
	"IEF572I": "[jobname.stepname] VOLUME VERIFICATION ERROR ON ser",
	"IEF602I": "EXCESSIVE NUMBER OF EXECUTE STATEMENTS",
	"IEF604I": "EXPDT SUBPARAMETER OF LABEL KEYWORD SPECIFIES ZERO DAYS VALUE",
	"IEF606I": "MISPLACED DD STATEMENT",
	"IEF617I": "NO NAME ON FIRST DD STATEMENT AFTER EXEC STATEMENT",
	"IEF619I": "SUBPARAMETER IN SYSOUT FIELD IS MUTUALLY EXCLUSIVE WITH SUBPARAMETER IN DEST FIELD",
	"IEF623I": "SOURCE TEXT CONTAINS UNDEFINED OR ILLEGAL CHARACTERS text",
	"IEF624I": "INCORRECT USE OF PERIOD text",
	"IEF625I": "INCORRECT USE OF PARENTHESIS IN THE parameter FIELD",
	"IEF631I": "NUMBER OF DDNAMES EXCEEDS MAXIMUM",
	"IEF632I": "FORMAT ERROR text",
	"IEF633I": "PROGRAMMER NAME MISSING text",
	"IEF634I": "ACCOUNT NUMBER MISSING text",
	"IEF635I": "JOBNAME MISSING text",
	"IEF636I": "MISPLACED JOBLIB STATEMENT",
	"IEF637I": "EXCESSIVE ACCOUNT FIELD LENGTH text",
	"IEF638I": "SPECIFIED NUMERIC EXCEEDS MAXIMUM ALLOWED text",
	"IEF639I": "INVALID CLASS DESIGNATION text",
	"IEF640I": "EXCESSIVE NUMBER OF POSITIONAL PARAMETERS text",
	"IEF641I": "IMPROPER SUBPARAMETER LIST text",
	"IEF642I": "EXCESSIVE PARAMETER LENGTH text",
	"IEF643I": "UNIDENTIFIED POSITIONAL PARAMETER text",
	"IEF644I": "INVALID NUMERIC text",
	"IEF645I": "INVALID REFER BACK text",
	"IEF646I": "REQUIRED POSITIONAL PARAMETER MISSING text",
	"IEF647I": "FIRST CHARACTER OF NAME NOT ALPHABETIC OR NOT NATIONAL text",
	"IEF648I": "INVALID DISP FIELD - {KEEP|PASS} SUBSTITUTED",
	"IEF649I": "EXCESSIVE NUMBER OF DD STATEMENTS",
	"IEF650I": "INCORRECT USE OF SLASH xxx",
	"IEF653I": "SUBSTITUTION JCL - text",
	"IEF654I": "MULTIPLE DDNAMES REFER TO ONE DD STATEMENT",
	"IEF655I": "INVALID DSNAME SPECIFIED WHEN SYSIN OR SYSOUT SPECIFIED",
	"IEF656I": "DD STATEMENT NAME INCONSISTENT WITH AMP",
	"IEF661I": "RESTART STEP NOT FOUND",
	"IEF667E": "ENF LISTEN EXIT ERROR FOR EVENT CODE xx",
	"IEF669I": "INVALID REFER FORWARD TO DYNAM DATA SET",
	"IEF670I": "NO VALUE ASSIGNED TO SYMBOLIC PARAMETER ON PROC STMT VIA THE EXEC STMT",
	"IEF671I": "MISPLACED JOBCAT DD STATEMENT",
	"IEF672I": "MULTIPLE STEPCAT DD STATEMENT IN STEP",
	"IEF673I": "ADDRSPC=REAL INVALID ON THE cntr STATEMENT",
	"IEF674I": "INVALID DYNAMNBR VALUE - 0 SUBSTITUTED",
	"IEF675I": "PERFORM VALUE INVALID OR OMITTED - SYSTEM DEFAULT SUBSTITUTED",
	"IEF677I": "WARNING MESSAGE(S) FOR JOB jobname ISSUED",
	"IEF679I": "DEVICE I/O ERROR CONVERTING/INTERPRETING JCL FOR JOB jobname",
	"IEF680I": "DEVICE I/O ERROR WRITING TO SYSTEM MESSAGE DATA SET FOR JOB jobname",
	"IEF681I": "INVALID COPIES VALUE - DEFAULT OF ONE SUBSTITUTED",
	"IEF682I": "FREE VALUE INVALID - DEFAULT OF (END) SUBSTITUTED",
	"IEF683I": "{CONVERTER | INTERPRETER} TERMINATED DUE TO abendcde ABEND REASON=reason-code",
	"IEF684I": "HOLD VALUE INVALID - DEFAULT OF ‘NO’ SUBSTITUTED",
	"IEF685I": "STATIC PLUS DYNAMIC DD COUNT EXCEEDS MAX - DYNAMIC DD'S REDUCED",
	"IEF686I": "DDNAME REFERRED TO ON DDNAME KEYWORD IN PRIOR STEP WAS NOT RESOLVED",
	"IEF687I": "jobname [procstep] stepname ddname [+ xxx] - REQUESTED VOLUME MOUNTED ON JES3 MANAGED UNIT",
	"IEF688I": "jobname [procstep] stepname ddname [+ xxx] - NULLFILE AND DSNAME CONFLICT IN ISAM CONCATENATION",
	"IEF689I": "JOB jjjjjjjj FAILED ddname DID NOT OPEN",
	"IEF690I": "FOLLOWING VOLUMES UNAVAILABLE TO jobname stepname ser1 ser2 … ser9",
	"IEF691I": "jobname [procstep] stepname ddname[+ xxx] - DATA SET/VOLUME COULD NOT BE RACF PROTECTED - USER NOT DEFINED TO RACF",
	"IEF692I": "INVALID REFERENCE TO HIERARCHICAL FILE [text]",
	"IEF694I": "DDNAME REFERENCE TO DD CONCATENATION REFERS ONLY TO FIRST DD",
	"IEF695I": "START mbrname WITH JOBNAME jobname IS ASSIGNED TO USER userid ,GROUP groupid",
	"IEF696I": "I/O TIMEOUT ON DEVICE dev - DEVICE MARKED NOT READY",
	"IEF700I": "jobname [procstep] stepname - ENVIRONMENT CHANGED. NOW UNABLE TO ALLOCATE",
	"IEF701I": "jobname [procstep] stepname [ddname[+ xxx]] - ERROR CHANGING ALLOCATION ASSIGNMENTS",
	"IEF702I": "jobname [procstep] stepname ddname [+ xxx] UNABLE TO ALLOCATE",
	"IEF703I": "- jobname [procstep] stepname ddname[+ xxx] - NEW DATA SETS NOT ALLOWED ON STACKED PACK FORMAT DOS VOLUME",
	"IEF704I": "jobname [procstep] stepname ddname[+ xxx] - UNABLE TO ACCESS REQUIRED SYSCTLG DATA SET ON CONTROL VOLUME",
	"IEF705I": "DIAGNOSTIC INFORMATION FOR UNSUCCESSFUL ALLOCATION DETECTED AT date time BY module INSTANCE instance jobname [procstep] stepname ddname  [+xxx][DEVICES FOR unitname - TOTAL: nnn / OFFLN: nnn / ALLOC: nnn / AVAIL: nnn]DIAGNOSTIC UNIT/DEVICE TYPE INFO: unitinfo[DEFAULT UNIT APPLIED FROM [PARMLIB|USER PROFILE]][STORCLAS: storclas DATACLAS: dataclas MGMTCLAS: mgmtclas][DYNAMIC ALLOCATION REQUEST FLAGS: flg1 flg2]",
	"IEF706I": "EDT BUILT FROM THIS IODF MAY CAUSE DEVICE ALLOCATION FAILURES ON RELEASES PRIOR TO HBB7730.",
	"IEF707I": "INTERNAL ALLOCATION ERROR description",
	"IEF713I": "jobname [procstep] stepname - MSS VOLUME NOT AVAILABLE",
	"IEF714I": "jobname [procstep] stepname - MSS VOLUME NOT DEFINED",
	"IEF715I": "jobname [procstep] stepname - MSS VOLUME INACCESSIBLE",
	"IEF716I": "jobname [procstep] stepname - UNABLE TO MOUNT MSS VOLUME",
	"IEF717I": "jobname [procstep] stepname - MSS VOLUME NOT MOUNTED. MSVGP NAME DOES NOT EXIST.",
	"IEF718I": "jobname [procstep] stepname - MSS VOLUME NOT MOUNTED. SPACE OR MSVGP REQUIRED FOR NON-SPECIFIC REQUEST.",
	"IEF719I": "jobname [procstep] stepname ddname [+ xxx] - DATA SET PREVIOUSLY DEFINED",
	"IEF720I": "jobname [procstep] stepname ddname [+ xxx] - USER NOT AUTHORIZED TO DEFINE THIS DATA SET",
	"IEF721I": "jobname [procstep] stepname ddname [+ xxx] - PROTECTION CONFLICT IN ISAM REQUESTS",
	"IEF722I": "jobname - FAILED - text",
	"IEF723E": "ERROR OCCURRED IN ENF MODULE name",
	"IEF724I": "jobname [procstep] stepname ALLOCATION OF STEPCAT(S) FOR DISPOSITION PROCESSING FAILED",
	"IEF725I": "jobname [procstep] stepname ddname [+ xxx] - MSS VOLUME SELECTION FAILURE - rc",
	"IEF726I": "jobname [procstep] stepname ddname [+ xxx] - ALLOCATION REQUEST FAILURE - MSS NOT INITIALIZED",
	"IEF729I": "stmt STATEMENT IGNORED, NOT SUPPORTED FOR DYNAMIC UPDATE",
	"IEF730I": "INVALID REPLY SPECIFIED.",
	"IEF731I": "SCHEDxx LINE num: PPT STMT [FOR PGMNAME name] [IGNORED. | ACCEPTED.] REASON = kwrc.",
	"IEF732I": "SCHEDxx LINE num: DUPLICATE PPT STMT FOR PGMNAME name IGNORED.",
	"IEF734I": "SCHEDxx LINE num:[RESTART|NORESTART] [CODE cde|STATEMENT] [IGNORED|ACCEPTED]. REASON=kyrc",
	"IEF735I": "IEFSSNyy: PRIMARY IGNORED. PREVIOUSLY SPECIFIED IN IEFSSNzz",
	"IEF736A": "SPECIFY PRIMARY SUBSYSTEM NAME",
	"IEF737I": "IEFSSNxx LINE nnnn: KEYWORD keyword IGNORED. NOT RECOGNIZED.",
	"IEF738I": "mem LINE num:[RESTART|NORESTART] STMT IGNORED. NO OPERANDS SPECIFIED.",
	"IEF739D": "CONFIGURATION CHANGE DELAYED DUE TO EXCESSIVE WAIT ON PREVIOUS EDT - REPLY ‘WAIT’ OR ‘TERM’.",
	"IEF740I": "jobname [procstep] stepname ddname [+ xxx] - DATA SET/VOLUME COULD NOT BE RACF PROTECTED. RACF NOT ACTIVE",
	"IEF741I": "jobname [procstep] stepname ddname[+ xxx] - PROTECT REQUEST FAILED - INVALID DATA SET/VOLUME SPECIFICATION",
	"IEF742I": "jobname [procstep] stepname - STEP IN ALLOCATION BEFORE SYSTEM RESTART - NO AUTOMATIC RESTART",
	"IEF743I": "jobname FORCED - CODE SA22 - IN ADDRESS SPACE asid",
	"IEF751I": "jobname [procstep] stepname - JOB FAILED BY SUBSYSTEM",
	"IEF752I": "jobname [procstep] stepname ddname[+ xxx] - REQUEST FAILED BY SUBSYSTEM",
	"IEF753I": "jobname [procstep] stepname ddname[+ xxx] - REQUEST FAILED - SUBSYSTEM DOES NOT SUPPORT ALLOCATION",
	"IEF754I": "jobname [procstep] stepname ddname [+ xxx] - REQUEST FAILED - SUBSYSTEM IS NOT OPERATIONAL",
	"IEF755I": "jobname [procstep] stepname ddname[+ xxx] - REQUEST FAILED SUBSYSTEM DOES NOT EXIST",
	"IEF756I": "jobname [procstep] stepname ddname[+ xxx] - REQUEST FAILED - SYSTEM ERROR IN PROCESSING SUBSYS DD PARAMETER",
	"IEF757I": "ILLEGAL DATA SET NAME ON DD STATEMENT",
	"IEF758I": "SUBSYSTEM AVAILABILITY LIMITED text",
	"IEF759I": "[xxxx] SUBSYSTEM UNAVAILABLE, text",
	"IEF760I": "ERROR IN memname, CODE=yyyrc incorrect-record",
	"IEF761I": "jobname [procstep] stepname ddname callername DD IS ALREADY ALLOCATED AND WILL BE USED BY THIS TASK",
	"IEF764I": "jobname [procstep] stepname ddname callername PARMLIB READ FAILED - MEMBER membername NOT FOUND",
	"IEF765I": "jobname [procstep] stepname ddname callername PARMLIB READ FAILED FOR MEMBER membername DUE TO AN I/O ERROR.",
	"IEF766I": "jobname [procstep] stepname ddname callername PARMLIB READ FAILED FOR MEMBER membername DUE TO AN OPEN ERROR.",
	"IEF767I": "jobname [procstep] stepname ddname callername ALLOCATE FAILED FOR dsname",
	"IEF768I": "jobname [procstep] stepname ddname callername CONCATENATION OF THE LOGICAL PARMLIB FAILED.",
	"IEF769I": "jobname [procstep] stepname callername LOADING OF THE PARMLIB READ ROUTINE FAILED.",
	"IEF770I": "jobname [procstep] stepname ddname callername UNABLE TO ACCESS THE LOGICAL PARMLIB.",
	"IEF771I": "dev [PENDING] OFFLINE - {ASSIGNED TO ANOTHER SYSTEM| ASSIGN FAILED, RETURN CODE=return-code}",
	"IEF772I": "dev PENDING OFFLINE - MUST BE VARIED OFFLINE TO JES3",
	"IEF773I": "TIOT SIZE = xxxxK, MAXIMUM SINGLE UNIT DD ENTRIES = zzzzzzzz",
	"IEF775I": "jobname [procstep] stepname ddname callername UNALLOCATION OF THE LOGICAL PARMLIB FAILED - NOT CLOSED.",
	"IEF776I": "jobname [procstep] stepname ddname callername UNALLOCATION OF THE LOGICAL PARMLIB FAILED.",
	"IEF777I": "jobname [procstep] stepname ddname callername PARMLIB READ ROUTINE RECEIVED A BAD PARAMETER LIST.",
	"IEF778I": "FURTHER INFORMATION NOT PROVIDED BY SUBSYSTEM ssnm",
	"IEF779I": "dddd, VOLUME vvvvvv PENDING OFFLINE BY callerid",
	"IEF781I": "jobname [procstep] stepname callername LIST BUFFER INPUT TO LOGICAL PARMLIB SERVICE IS NOT ACCESSIBLE.",
	"IEF783I": "jobname [procstep] stepname callername READ BUFFER INPUT TO LOGICAL PARMLIB SERVICE IS NOT ACCESSIBLE.",
	"IEF786I": "ERROR VERIFYING INTERNAL VOLUME LABEL ser ON DEVICE dev",
	"IEF787I": "jobname stepname - ERROR VERIFYING INTERNAL LABEL OF VOLUME ser ON DEVICE dev. ERROR READING LABEL.",
	"IEF788I": "jobname stepname - ERROR VERIFYING INTERNAL LABEL OF VOLUME ser ON DEVICE dev. INVALID LABEL TYPE.",
	"IEF789I": "jobname stepname - ERROR VERIFYING INTERNAL LABEL OF VOLUME ser ON DEVICE dev. SL TAPE MOUNTED BUT AL REQUESTED.",
	"IEF790I": "jobname stepname - ERROR VERIFYING INTERNAL LABEL OF VOLUME ser ON DEVICE dev. AL TAPE MOUNTED BUT SL REQUESTED.",
	"IEF791I": "jobname stepname - ERROR VERIFYING INTERNAL LABEL ser ON DEVICE dev.",
	"IEF811I": "DUPLICATE VERB AND LABEL text",
	"IEF812I": "JCL USAGE LIMITED - SYSTEM ERROR",
	"IEF815I": "INVALID HEXADECIMAL VALUE IN THE parameter FIELD",
	"IEF817I": "PARAMETER LENGTH LESS THAN MINIMUM ALLOWED IN THE parameter FIELD",
	"IEF818E": "JCL USAGE LIMITED - text",
	"IEF819I": "EXCESSIVE NUMBER OF POSITIONAL PARAMETERS IN SUBPARAMETER LIST IN THE parameter FIELD",
	"IEF820I": "SPECIFIED NUMERIC LESS THAN MINIMUM ALLOWED IN THE parameter FIELD",
	"IEF823I": "NUMBER OF LEVELS EXCEEDS MAXIMUM IN THE parameter FIELD",
	"IEF824I": "LENGTH OF LEVEL xx EXCEEDS yy IN THE parameter FIELD",
	"IEF825I": "INVALID CHARACTER IN THE parameter FIELD",
	"IEF861I": "FOLLOWING RESERVED DATA SET NAMES UNAVAILABLE TO jobname",
	"IEF863I": "DSN=dsname jobname RC=returncodeRSN=reasoncode FROM SERVICE servicename",
	"IEF874I": "jjj proc sss ddname ALLC_OFFLN EXIT CHOSE \"BRING DEVICE ONLINE\" WITHOUT SPECIFYING ANY DEVICE NUMBER",
	"IEF875I": "jobname [procstep] stepname ddname[+ xxx] ALLOC_OFFLN EXIT CHOSE \"ISSUE WTOR\" AND EXCLUDED ALL DEVICES IN THE DEVICE LIST",
	"IEF876I": "jobname [procstep] stepname JOB CANCELLED BY {VOLUME_ENQ} INSTALLATION {POLICY|EXIT}",
	"IEF877E": "jobname NEEDS xxx UNIT(S) FOR stepname procname ddname[ +zzz] [[FOR VOLUME(S): ser, [ser, [,…,ser]] [SCRTCH-nnn] [PRIVAT-nnn]] | [LIBRARY: libname LIBRARY STATUS: status]] state1[dev[dev … dev]]⋮state2[dev[dev … dev]]⋮staten[dev[dev … dev]]⋮",
	"IEF878I": "END OF IEF877E FOR jobname stepname procname ddname [+zzz .]",
	"IEF879I": "dddd PENDING OFFLINE BY callerid",
	"IEF880I": "dddd NOW OFFLINE BY callerid [-DEVICE IS BOXED]",
	"IEF881I": "cmd COMMAND FOR DEVICE devn FAILED - ABEND abcd, REASON rsn",
	"IEF882E": "jobname [procstep] stepname IS WAITING FOR A REPLY TO pmsgid",
	"IEF883E": "jobname [procstep] stepname IS WAITING FOR DEVICE(S) WHILE HOLDING SYSTEM RESOURCES",
	"IEF893I": "CONCATENATE REQUEST FAILED - CORRESPONDING DSABS RESIDE IN BOTH ABOVE AND BELOW THE LINE STORAGE. CONSISTENT STORAGE LOCATIONS ARE REQUIRED.",
	"IEF894I": "COMPONENT TRACE PARMLIB OPTION optname IS NOT VALID.",
	"IEF895I": "SYSIEFAL CTRACE DEFINITION FAILED. RC = rc, RSN = rsn.",
	"IEF896I": "UNABLE TO OBTAIN SYSIEFAL CTRACE BUFFER MAXIMUM SIZE OF hexnum BYTES",
	"IEF897I": "SYSIEFAL CTRACE DEFINITION FAILED USING CTIIEFAL. RC = rc, RSN = rsn.",
	"IEF898I": "jobname stepname procstep ddname [+ xxx] FAILED TO ALLOCATE - SPECIFIED ESOTERIC HAS TAPE AND NONTAPE DEVICES",
	"IEF900I": "SYSTEM SYMBOLS WERE UPDATED FROM memname",
	"IEF901I": "SYSTEM SYMBOLS WERE NOT UPDATED FROM memname. text",
	"IEF910I": "PARMDD DATA SET UNUSABLE.",
	"IEF911I": "EXCESSIVE USER PARAMETER STRING LENGTH.",
	"IEF990I": "CANNOT DETERMINE VOLUME CORRESPONDING TO DEVICE sdddd",
}

var abaMessages = map[string]string{
	"ABA001I": "AGGREGATE BACKUP ASSIST V1.O STARTING — ll",
	"ABA002S": "OPEN ERROR ON FILE ddname",
	"ABA003S": "UNABLE TO OBTAIN SUFFICIENT STORAGE. nnnnnnnn BYTES REQUIRED. RS=ssss",
	"ABA004I": "JOB NAMES FOUND IN SMF DATA BY ABA:",
	"ABA005S": "ERROR RETURN FROM DFSORT. RETURN CODE cc",
	"ABA006S": "INVALID SELECTION DATA SET SPECIFIED. RECORD FORMAT NOT FIXED, FIXED BLOCK, OR RECORD LENGTH NOT 80",
	"ABA007S": "INPUT JOB NAME FILTER HAS INVALID FORMAT: ffffffff",
	"ABA008I": "SYSIN INPUT DATA:",
	"ABA009I": "TOTAL NUMBER OF DATA SETS FOUND: nnnnnnnn",
	"ABA010I": "TOTAL NUMBER OF JOBS FOUND: nnnnnnnn",
	"ABA020I": "STORAGE USED, LOCATION — ANY: nnnnnnnn bytes",
	"ABA021I": "STORAGE USED, LOCATION — BELOW: nnnnnnnn BYTES",
	"ABA030I": "NUMBER OF RECORDS PASSED TO SORT: nnnnnnnn",
	"ABA031I": "NUMBER OF RECORDS RECEIVED FROM SORT: nnnnnnnn",
	"ABA032E": "ERROR, RECORDS LOST DURING SORT PROCESSING",
	"ABA033I": "SORT CNTL STMT: ssssssss....",
	"ABA040W": "WARNING, RECORD FORMAT ERRORS FOUND IN SMF DATA SET",
	"ABA050I": "AGGREGATE BACKUP ENTERING {SMF PROCESSING | LOCATE PROCESSING | SORT PROCESSING} yy.ddd.hh.mm.ss",
	"ABA098I": "ABA ENDING",
	"ABA099S": "ABA TERMINATING",
}
